# The testing matrix considers ruby/puppet versions supported by SIMP and PE:
# ------------------------------------------------------------------------------
# Release       Puppet   Ruby    EOL
# SIMP 6.4      5.5      2.40    TBD
# PE 2018.1     5.5      2.40    2021-01 (LTS overlap)
# PE 2019.8     6.18     2.5     2022-12 (LTS)
#
# https://puppet.com/docs/pe/2018.1/component_versions_in_recent_pe_releases.html
# https://puppet.com/misc/puppet-enterprise-lifecycle
# https://puppet.com/docs/pe/2018.1/overview/getting_support_for_pe.html
# ==============================================================================

name: Validation and Tests
# Controls when the action will run.
on:
  push: {}
  pull_request: {}
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:   
  validate:
    name: "Validation"
    runs-on: ubuntu-latest
    env:
      PUPPET_VERSION: "~> 6"
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:           
      - uses: actions/checkout@v2
      - name: "Install Ruby ${{matrix.puppet.ruby_version}}"
        uses: ruby/setup-ruby@v1  # ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
        with:
          ruby-version: 2.5        
      - uses: actions/cache@v2
        with:
          path: .vendor
          key: ${{ runner.os }}-gems-ruby${{matrix.puppet.ruby_version}}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-ruby${{matrix.puppet.ruby_version}}-
      - name: "Bundle dependencies for Puppet ${{matrix.puppet.puppet_version}}"
        run: |
          bundle config path .vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: "Validation"
        run: |
          bundle exec rake syntax
          bundle exec rake lint
          bundle exec rake metadata_lint

      - name: "RELENG checks (files)"
        run: |
          bundle exec rake check:dot_underscore
          bundle exec rake check:test_file

      - name: "RELENG checks (tags)"
        run: |
          bundle exec rake pkg:check_version
          bundle exec rake pkg:compare_latest_tag
          bundle exec rake pkg:create_tag_changelog
          
      - name: "RELENG checks (build)"
        run: |
          bundle exec pdk build --force
          #wget https://apt.puppet.com/puppet-tools-release-bionic.deb
          #sudo dpkg -i puppet-tools-release-bionic.deb
          #sudo apt-get update 
          #sudo apt-get install pdk
          #rm -f Gemfile.lock


  test:  # <-- can be anything
    name: "Spec/Unit Tests"
    needs: validate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        puppet:
          - label: "SIMP 6.4/PE 2018.1"
            puppet_version: "~> 5.5.21"
            ruby_version: "2.4"
          - label: "SIMP 6.5/PE 2019.8"
            puppet_version: "~> 6.18.0"
            ruby_version: "2.5"
    env:
      PUPPET_VERSION: "${{matrix.puppet.puppet_version}}"    

    steps:
      - uses: actions/checkout@v2
      - name: "Install Ruby ${{matrix.puppet.ruby_version}}"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{matrix.puppet.ruby_version}}
      - uses: actions/cache@v2
        with:
          path: .vendor
          key: ${{ runner.os }}-gems-ruby${{matrix.puppet.ruby_version}}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-ruby${{matrix.puppet.ruby_version}}-${{ hashFiles('**/Gemfile.lock') }}
            ${{ runner.os }}-gems-ruby${{matrix.puppet.ruby_version}}-
      - name: "Bundle dependencies for Puppet ${{matrix.puppet.puppet_version}}"
        run: |
          bundle config path .vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: "Ensure `rpm` command is available"
        run: "command -v rpm || if command -v apt-get; then apt-get update; apt-get install -y rpm; fi ||:"

      - name: "Run Spec/Unit tests for ${{matrix.puppet.label}}"
        run: |
          bundle exec rake spec
          echo Hello, world!  ${{matrix.puppet.label}}

  # TODO: only run when org member initiates action?      
  acceptance:  # <-- can be anything
    name: "Acceptance tests"
    needs: [validate, test]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        puppet:
          - label: "SIMP 6.4/PE 2018.1"
            puppet_version: "~> 5.5.21"
            ruby_version: "2.4"
          - label: "PE 2019.2"
            puppet_version: "~> 6.17.0"
            ruby_version: "2.5"    
    env:
      PUPPET_VERSION: "${{matrix.puppet.puppet_version}}"    

    steps:
      - uses: actions/checkout@v2
      - name: "Install Ruby ${{matrix.puppet.ruby_version}}"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{matrix.puppet.ruby_version}}
      - uses: actions/cache@v2
        with:
          path: .vendor
          key: ${{ runner.os }}-gems-ruby${{matrix.puppet.ruby_version}}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-ruby${{matrix.puppet.ruby_version}}-
      - name: "Bundle dependencies for Puppet ${{matrix.puppet.puppet_version}}"
        run: |
          bundle config path .vendor/bundle
          bundle install --jobs 4 --retry 3
          
      - name: "Run Acceptance tests for ${{matrix.puppet.label}}"
        run: | 
          echo bundle exec rake beaker:suite[TODO:matrix_thing_here]

