# From https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#job-context
---
on: push

jobs:
  one:
    runs-on: ubuntu-16.04
    steps:
      - name: Dump contexts
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
  member_check:
    name: Member check
    runs-on: ubuntu-latest
    steps:
      - name: Check if organization member
        id: is_organization_member
        if: github.event.action == 'push'
        #uses: jamessingleton/is-organization-member@v1
        uses: jamessingleton/is-organization-member@3c9963089f1fade125df64983be54219d99fa9bd
        with:
          organization: simp
          username: ${{ github.actor }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Comment
        if: |
          steps.is_organization_member.outputs.result == false
        run: echo "DENIED User Does Not Belong to testorg"
      - name: Create Comment
        if: |
          steps.is_organization_member.outputs.result == true
        run: echo "GOOD User Belongs to testorg"
