# From https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#job-context
---
on: push

jobs:
  member_check1:
    name: Member check (github-script)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        id: user-membership
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            // See: https://octokit.github.io/rest.js/
            ////console.log("========== REPO:", context.repo)
            ////console.log("========== REPO OWNER: ", context.repo.owner)
            console.log("========== PAYLOAD: ", context.payload)
             // See: https://docs.github.com/en/free-pro-team@latest/rest/reference/projects#get-project-permission-for-a-user
            const project_permission = await github.request('GET /repos/{owner}/{repo}/collaborators/{username}/permission', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              username: context.payload.sender.login,
              mediaType: {
                previews: [
                  'inertia'
                ]
              }
            })
            console.log("========== PROJ PERMISSION (SHORT): ", project_permission.data.permission)
            
            // See: https://docs.github.com/en/free-pro-team@latest/rest/reference/teams#get-team-membership-for-a-user
            const team_membership = await github.request('GET /orgs/{owner}/teams/{team_slug}/memberships/{username}', {
              owner: context.repo.owner,
              team_slug: 'reviewers'
              username: context.payload.sender.login,
              mediaType: {
                previews: [
                  'inertia'
                ]
              }
            })
            console.log("========== TEAM MEMBERSHIP: ", team_membership)
            


  member_check2:
    name: Member check (is-organization-member)
    runs-on: ubuntu-latest
    steps:
      - name: Check if organization member
        id: is_organization_member
        if: github.event.action == 'push'
        #uses: jamessingleton/is-organization-member@v1
        uses: jamessingleton/is-organization-member@3c9963089f1fade125df64983be54219d99fa9bd
        with:
          organization: simp
          username: ${{ github.actor }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Comment (PASS)
        if: steps.is_organization_member.outputs.result == 'true'
        run: |
           echo "GOOD User Belongs to simp"
      - name: Create Comment (DENIED)
        if: steps.is_organization_member.outputs.result == 'false'
        run: |
           echo "DENIED User Does Not Belong to simp"
  one:
    runs-on: ubuntu-16.04
    steps:
      - name: Dump contexts
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
